version: "3.7"

services:    
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        volumes:
            - how-are-you-redis-volume:/bin/data

    api:
        build: .
        command: python main.py
        image: how-are-you-img
        ports:
            - "8000:8000"
        volumes:
            - how-are-you-api-volume:/bin/data
        env_file:
            - "./.local.env"
        depends_on:
            - redis

volumes:
    how-are-you-redis-volume:
    how-are-you-api-volume: