version: "3.7"

services:    
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        volumes:
            - how-are-you-test-redis-volume:/bin/data

volumes:
    how-are-you-test-redis-volume:
